### ISSUE TITLE
Sync with DynamoDB

### ISSUE THREAD

**Issue by tlindsay42** [xbrowsersync/api#18]
Any interest in adding support for DynamoDB for the persistence tier?

**Comment by nero120** [comment]
No plans to support any other dbs @tlindsay42, especially since using [Docker](https://hub.docker.com/r/xbrowsersync/api) makes it so easy to stand up a fully configured service. Adding support for other dbs would increase the effort to support current/future releases for no significant functional gain.

However, I do plan to add support for syncing to other popular cloud data services, such as [Nextcloud](https://nextcloud.com/), or [Dropbox](https://www.dropbox.com/). That way, users who want to retain their own data can either run their own xBrowserSync service, or if they prefer to store their data via a third-party cloud service then they can do this instead. I think that should cover enough use cases.

Hope that clears things up! 😄

**Comment by tlindsay42** [comment]
Fair enough. Thanks @nero120! 😄
