### ISSUE TITLE
Support xbrowsersync 

### ISSUE THREAD

**Issue by lordvalium** [xbrowsersync/api#34]
Hi, 
i want to support the project with my server. Have docker running on ubuntu 18.04. 

- Is it possible to just take my IP in .env?

- this tutorial https://github.com/xbrowsersync/api-docker/blob/master/README.md points to https://github.com/xbrowsersync/api and vice versa. 

Can you just give a simple tut how to use the docker? Dont understand it tough :)

thx

**Comment by nero120** [comment]
Hi @lordvalium, thanks for your interest in xBrowserSync! I strongly recommend following a docker tutorial like [this one](https://www.tutorialspoint.com/docker/index.htm) to get to grips with what docker is and how it works before trying to run an xBrowserSync service in docker. Also, it's a good idea to understand what docker compose is as well, tutorial [here](https://www.tutorialspoint.com/docker/docker_compose.htm).

I don't have any spare capacity to produce more tutorials, but once you understand docker you should find it very straightforward to follow the steps in [Running a production-ready service](https://github.com/xbrowsersync/api-docker/blob/master/README.md#running-a-production-ready-service).

> Is it possible to just take my IP in .env?

No, you need to provide a hostname so that traefik knows which requests to route to the service..
