### ISSUE TITLE
Safari  and iOS support?

### ISSUE THREAD

**Issue by JBFUK** [xbrowsersync/api#55]
I was really excited about this extension which might help me finally dump Chrome, but alas, no Apple support.  So close.. 

Are you really sure you won't support iOS and Safari because of a silly $99/yr licensing cost?  

Us Apple users are clearly not going to migrate to an inferior platform (android) in order to get this extension but I'm sure there are many who would happily donate to the project to have their device supported.  Even if you just supported Safari on OS X it would provide a means of syncing bookmarks to our iOS devices too (via iCloud).

Would you reconsider if there was enough demand?

**Comment by maitrenageur** [comment]
Yes, I'm on the side by @JBFUK . For me a Safari support would be enough for the first step. And I would donate for a license.

**Comment by nero120** [comment]
Sorry guys, it's not just the dev license but also it's the time and effort to develop and maintain a completely different codebase because Apple decided they didn't want to use the common Web Extensions platform for Safari. The only thing that allows me to develop and support xBrowserSync is that I can use a common codebase for all platforms, but Apple breaks this. Plus, in order to deploy apps to the App Store you have to develop (publish at least) them using Apple hardware. I'm just not interested in supporting such a monopolistic coporation that even manages to make Google and Microsoft look good.

However, I do have plans to release a PWA that will be hosted online so at least Apple users can use that.

**Comment by maitrenageur** [comment]
@nero120 Thank you for your feedback. Sorry, what is the meaning of PWA?

**Comment by nero120** [comment]
@maitrenageur sorry, it stands for [Progressive Web App](https://superpwa.com/doc/test-pwa-ios-devices/). Essentially, it's a way of making a web site look and feel a bit more like a native app, it's a great compromise that avoids having to rebuild a native version of an app.

**Comment by maitrenageur** [comment]
@nero120 Means, as interims or bypass solution a planned web based app (PWA) shows my bookmarks in a direct dialogue with my xBrowserSync-Server. This PWA is parallel open (as separate App) to my Browser (e.g. Safari) and i can manage (new) bookmarks between both apps, the browser and the PWA. Is this correct explained?

**Comment by maitrenageur** [comment]
@nero120 Sorry, please can you reopen this topic as issue?

**Comment by nero120** [comment]
@maitrenageur sorry Safari/iOS support is never coming so the issue should remain closed. Feel free to continue to post messages here though.

The PWA is a separate component and is supported by multiple platforms, including iOS. It will have the same functionality as the web extension.
